In [26]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.mixture import GaussianMixture
from sklearn.metrics import accuracy_score
from sklearn.metrics import pairwise_distances_argmin

In [3]:
# 加载数据
iris = load_iris()
X = iris.data
Y = iris.target

In [33]:
# 数据预处理
ss = StandardScaler()
X = ss.fit_transform(X)
x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=9)

In [34]:
# 构建模型
gmm = GaussianMixture(n_components=3, max_iter=1000, random_state=9)
gmm.fit(x_train)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=1000,
                means_init=None, n_components=3, n_init=1, precisions_init=None,
                random_state=9, reg_covar=1e-06, tol=0.001, verbose=0,
                verbose_interval=10, warm_start=False, weights_init=None)

In [37]:
means = gmm.means_
y_test_hat = gmm.predict(x_test)
y_hat = gmm.predict(X)

In [38]:
means

array([[-0.7520501 ,  1.40968193, -1.29608259, -1.22106479],
       [ 0.53581282, -0.36772453,  0.66620101,  0.63841951],
       [-1.3858922 ,  0.26212949, -1.34176623, -1.30696273]])

In [39]:
y_test_hat

array([1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 0,
       1, 0, 1, 1, 0, 1, 2, 1])

In [40]:
y_test

array([2, 1, 2, 2, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0,
       2, 0, 2, 1, 0, 2, 0, 2])

In [10]:
# 画图
plt.rcParams['font.sans-serif'] = ['Heiti']
plt.rcParams['axes.unicode_minus'] =False

%matplotlib tk

In [14]:
fig = plt.figure(facecolor='w')

ax = fig.add_subplot(111, projection='3d')
ax.scatter(X[y_hat==0, 0], X[y_hat==0, 1], X[y_hat==0, 2], cmap='cool')
ax.scatter(X[y_hat==1, 0], X[y_hat==1, 1], X[y_hat==1, 2], cmap='cool')
ax.scatter(X[y_hat==2, 0], X[y_hat==2, 1], X[y_hat==2, 2], cmap='cool')

In [23]:
# 准确率
means_ = np.array([np.mean(X[Y==i], axis=0) for i in range(3)])

In [24]:
means_

array([[-1.01457897,  0.85326268, -1.30498732, -1.25489349],
       [ 0.11228223, -0.66143204,  0.28532388,  0.1667341 ],
       [ 0.90229674, -0.19183064,  1.01966344,  1.08815939]])

In [25]:
means

array([[-0.7520501 ,  1.40968193, -1.29608259, -1.22106479],
       [ 0.53581282, -0.36772453,  0.66620101,  0.63841951],
       [-1.3858922 ,  0.26212949, -1.34176623, -1.30696273]])

In [27]:
order = pairwise_distances_argmin(means_, means, axis=1, metric='euclidean')

In [41]:
y_hat_ = []
for i in y_hat:
    if i == 0:
        y_hat_.append(0)
    elif i == 1:
        y_hat_.append(2)
    elif i == 2:
        y_hat_.append(1)
    else:
        print('Error')

In [43]:
accuracy_score(Y, y_hat_)

0.5466666666666666